ex:
sample = ["jagadish very good","jagadish very bad"]
 
                    jagadish    very   good  bad   
        
jagadish very good     1         1       1    0 
jagadish very bad      1         1       0    1



In [1]:
sample = ["jagadish very good","jagadish very bad"]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
vec = CountVectorizer()
var = vec.fit_transform(sample)

In [6]:
var.toarray()

array([[0, 1, 1, 1],
       [1, 0, 1, 1]], dtype=int64)

In [7]:
import pandas as pd

D:\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [10]:
pd.DataFrame(var.toarray(),columns= vec.get_feature_names() )

bad  good  jagadish  very
0    0     1         1     1
1    1     0         1     1

In [9]:
vec.get_feature_names()

['bad', 'good', 'jagadish', 'very']

In [11]:
vec.vocabulary_

{'jagadish': 2, 'very': 3, 'good': 1, 'bad': 0}

In [14]:
vec.vocabulary_.get("very")

3

In [41]:
samplee = ['bilal is good good',
          'mouni is bad',
          'Prajna sings good pp',
          'she dances ']

In [42]:
count_vec = CountVectorizer()
val = count_vec.fit_transform(samplee)

In [43]:
val.toarray()

array([[0, 1, 0, 2, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [44]:
pd.DataFrame(val.toarray(),columns = count_vec.get_feature_names())

bad  bilal  dances  good  is  mouni  pp  prajna  she  sings
0    0      1       0     2   1      0   0       0    0      0
1    1      0       0     0   1      1   0       0    0      0
2    0      0       0     1   0      0   1       1    0      1
3    0      0       1     0   0      0   0       0    1      0

In [28]:
count_vec.transform(["iam very good"]).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [51]:
"iam very good" == "iam "+"very "+"good"

True

In [52]:
v = count_vec.build_analyzer()

In [56]:
v("iam very good") == ([ "iam","very","good"])

True