### Write a Python program to add, subtract, multiple and divide two Pandas      Series.
 Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


### Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10


1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [8]:
import numpy as np
m = np.ones((5,5))
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
m[1:-1,1:-1] =0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
mm = np.zeros((3,3))
np.pad(mm,pad_width=1,mode='constant',constant_values=1)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
m[]=0
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### find the indices of  non-zero elements [1,2,0,3,5,0,0,6]

In [24]:
li = [1,2,0,3,5,0,0,6]
np.nonzero(li)

(array([0, 1, 3, 4, 7], dtype=int64),)

In [14]:
import numpy as np
n=int(input())
m = np.ones((n,n))
a=n//2
m[a:-a,a:-a]=0
m

7


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### input : [2,3,1,4,8,2,4,3]
### output : [1,2,3,4,8,4,3,2]

In [22]:
li = [2,3,1,4,8,2,4,3,5]
sorted(li[:len(li)//2])+sorted(li[len(li)//2:],reverse = True)

[1, 2, 3, 4, 8, 5, 4, 3, 2]